server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: driftbox
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
            tag: attrs.tag
      - json:
          expressions:
            container: container_name
          source: tag
      - regex:
          expression: '.*driftbox-(?P<service>[a-z]+).*'
          source: container
      - labels:
          stream:
          service:
      - output:
          source: log