apiVersion: v1
kind: Secret
metadata:
  name: driftbox-secrets
  namespace: driftbox
type: Opaque
# All values must be base64 encoded
# To encode: echo -n "yourvalue" | base64
data:
  POSTGRES_USER: ZHJpZnRib3g=         # driftbox
  POSTGRES_PASSWORD: ZHJpZnRib3gxMjM= # driftbox123
  RABBITMQ_USER: ZHJpZnRib3g=         # driftbox
  RABBITMQ_PASSWORD: ZHJpZnRib3gxMjM= # driftbox123
  MINIO_ACCESS_KEY: ZHJpZnRib3gtYWNjZXNz       # driftbox-access
  MINIO_SECRET_KEY: ZHJpZnRib3gtc2VjcmV0MTIz   # driftbox-secret123
  JWT_SECRET: ZHJpZnRib3gtand0LXN1cGVyLXNlY3JldC1rZXktMjAyNA== # driftbox-jwt-super-secret-key-2024
  DATABASE_URL: cG9zdGdyZXNxbDovL2RyaWZ0Ym94OmRyaWZ0Ym94MTIzQHBvc3RncmVzcWw6NTQzMi9kcmlmdGJveA==
  RABBITMQ_URL: YW1xcDovL2RyaWZ0Ym94OmRyaWZ0Ym94MTIzQHJhYmJpdG1xOjU2NzI=