apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-service
  namespace: driftbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: share-service
  template:
    metadata:
      labels:
        app: share-service
    spec:
      containers:
        - name: share
          image: ghcr.io/BitGladiator/driftbox-share:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: driftbox-config
            - secretRef:
                name: driftbox-secrets
          env:
            - name: PORT
              value: "3005"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: share-service
  namespace: driftbox
spec:
  selector:
    app: share-service
  ports:
    - port: 80
      targetPort: 3005